name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install BLAS
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev
          sudo ln -s /usr/lib/x86_64-linux-gnu/libopenblas.so /usr/lib/x86_64-linux-gnu/libblas.so
          lake update

      - name: Set up Lean
        uses: leanprover/lean-action@v1

      - name: Build project
        run: lake build

      - name: Test project
        run: lake test

      - name: Upload Release Artifact
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.release.tag_name }}
        run: lake upload $TAG

  # build-windows:
  #   runs-on: windows-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Set up Lean
  #       uses: leanprover/lean-action@v1

  #     - name: Build project
  #       run: lake build

  #     - name: Test project
  #       run: lake test

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install BLAS
        run: |
          brew install openblas

      - name: Set up Lean
        uses: leanprover/lean-action@v1

      - name: Build project
        run: lake build

      - name: Test project
        run: lake test

      - name: Upload Release Artifact
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.release.tag_name }}
        run: lake upload $TAG
